Sprint 4/step 1
elrouss/react-burger pull request #20
Opened 2023-09-11 09:58 UTC by elrouss

1) Проект переписан на TypeScript;
2) Отрефакторена структура приложения.

2023-09-11 11:48 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали отличную и аккуратную работу по переводу вашего проекта на Typescript, все необходимые файлы охвачены, `any` не используются без необходимости, проведен большой рефакторинг с правильной структуризацией проекта,  **так держать** 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Использование null-assertion считается не совсем удачной практикой, т.к. возможны побочные эффекты в случае, если значение окажется пустым, плюс это ухудшает стабильность вашего кода. Поэтому, следует отказаться от таких выражений. (см. https://typescript-eslint.io/rules/no-non-null-assertion/)
- Следует улучшить типизацию для функции `checkResponse`, чтобы воспользоваться полностью возможностями TS для проверки качества и корректности вашего кода (подробнее в комментариях к файлу);
- В заказе следует отправлять 2 булки, также как они расположены в конструкторе ингредиентов
- Не следует хранить в компоненте "WithProtectedRoute" локальную логику, не связанную со статусом авторизации пользователя. Подробнее см. в комментариях к ревью

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-09-11 11:48 UTC, randomroot commented on src/components/app-header/app-header.tsx
> +              <li key={uuidv4()}>
🟡 **Можно улучшить:**

В качестве ключа можно использовать `url`, т.к. он будет уникальным

2023-09-11 11:48 UTC, randomroot commented on src/utils/api.ts
> +const checkResponse = (res: Response) =>
🔴 **Нужно исправить:**

В текущем виде функция `checkResponse` не конкретизирует тип возвращаемого значения в теле ответа, возвращая `Promise<any>`, поэтому все последующие функции связанные с ней работают с `any`, что не позволяет TypeScript отследить корректность вашего кода

**Чтобы улучшить данную ситуацию** вы можете воспользоваться следующим подходом:

На основе всех ответов из API вашего бэкенда вы можете обратить внимание, что они имеют схожую структуру с полем `success`, поэтому воспользовавшись пересечением типов получим универсальную структуру:

```typescript
type TResponse<T> = {
  success: boolean;
} & T;
```

где `T` - тип, в котором описаны остальные ключи запроса, например `{ accessToken: string, refreshToken: string }`, которую можно использовать в функции проверки успешности и вернуть назад конкретный тип, в случае успеха:

```typescript
const checkResponse = <T>(res: Response) => {
  return res.ok ? res.json().then(data => data as TResponse<T>) : Promise.reject(res.status);
};
```

2023-09-11 11:48 UTC, randomroot commented on src/services/features/user/api.ts
> +    const { accessToken, refreshToken } = await res.json();
🟡 **Можно улучшить:** 

Здесь и в других местах, где обрабатывается результат API - рекомендуется вернуться к использованию функции `checkResponse`, чтобы уменьшить дублирование кода, проверяющего результат запроса

2023-09-11 11:48 UTC, randomroot commented on src/services/features/current-ingredient/slice.ts
> +  ingredient: {
🟡 **Можно улучшить:**

В качестве начального состояния рекомендуется использовать значение `null` или `undefined`, чтобы в случае изменения структуры данных не приходилось каждый раз дополнять такой объект, плюс это исключит возможность ситуации, когда ошибочно будет посчитано, что данные есть

2023-09-11 11:48 UTC, randomroot commented on src/hooks/useFormData.tsx
> +  const [data, setData] = useState<IFormEntryData>({});
🟡 **Можно улучшить:**

Хук можно типизировать, если передать в него тип данных, которые будут использованы в форме. Так в вашем коде уменьшиться количество приведений к `unknown`

2023-09-11 11:48 UTC, randomroot commented on src/pages/home/home.tsx
> +      {(isLoading && <Preloader />) || <Shop />}
🟡 **Можно улучшить:**

Можно визуально упростить через тернарный оператор: `isLoading ? <Preloader /> : <Shop />`

2023-09-11 11:48 UTC, randomroot commented on src/hocs/withProtectedRoute.tsx
> +  if (hasForgottenPassword)
🔴 **Нужно исправить:**

Локальную логику связанную с восстановлением пароля следует перенести в соответствующие компоненты. Компонент `WithProtectedRoute` целесообразно задумать универсальным, главная задача которого пустить или не пустить пользователя в зависимости от статуса его авторизации, а дополнительные детали - лучше обрабатывать по конкретному урлу. Так проект будет проще поддерживать, а данный компонент, в случае появления новых кейсов - не будет разрастаться

2023-09-11 11:48 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.tsx
> +    const order = [selectedBun, ...selectedIngredients].map(
🔴 **Нужно исправить:**

В заказе следует отправлять 2 булки, также как они расположены в конструкторе ингредиентов

2023-09-11 11:48 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.tsx
> +        if (res.payload!.success) dispatch(RESET());
🔴 **Нужно исправить:**


Использование null-assertion (`!.`) считается не совсем удачной практикой, т.к. возможны побочные эффекты в случае, если значение окажется пустым, плюс это ухудшает стабильность вашего кода. Поэтому, следует отказаться от таких выражений. (см. https://typescript-eslint.io/rules/no-non-null-assertion/)

2023-09-11 11:48 UTC, randomroot commented on src/components/burger-constructor/selected-burger-ingredient/selected-burger-ingredient.tsx
> +  ingredient: IIngredient & { key: string };
🟡 **Можно улучшить:**

Тип ` IIngredient & { key: string };` можно вынести в отдельный именованный тип для удобства переиспользования

2023-09-11 17:59 UTC, elrouss commented
Михаил, добрый день!
Благодарю за ревью и ценные замечания. Постараюсь все учесть :)

2023-09-12 16:21 UTC, randomroot approved these changes
🟢 **Работа принята**

Все необходимые исправления были выполнены, функционал спринта был реализован, вопросов больше нет, предложены пара улучшений.

**Вы молодец, успехов в дальнейшем обучении!** 🐈

2023-09-12 16:21 UTC, randomroot commented on src/pages/reset-password/reset-password.tsx
> +  if (!hasForgottenPassword) navigate(ROUTES.sign.in);
🟡 **Можно улучшить:**

В этом случае лучше просто вернуть компонент `<Navigate />`

2023-09-12 16:21 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.tsx
> +    const order = [selectedBun, selectedBun, ...selectedIngredients].map(
🟡 **Можно улучшить:**

С точки зрения тех, кто будет собирать заказ, порядок не критичен, но им будет приятно, если последовательность будет сочетаться с режимом их работы :)

```jsx
[selectedBun, ...selectedIngredients, selectedBun]
```

2023-09-12 16:25 UTC, elrouss commented
Михаил, еще раз спасибо за ревью :))

2023-09-12 19:44 UTC, merged